import type { DiaryPreset } from "@/lib/diary-presets";
import type { FieldCadence, PatientSex } from "@/lib/types";

// Diary template library (PRD §5.9.1). Curated bundles of tracked fields that
// encode what people commonly track for a protocol or goal. A template is just
// metadata + existing-style DiaryPreset entries; confirming one creates ordinary
// tracked_fields rows. NOTHING here is generated by an LLM — this is a
// human-reviewed catalogue with the same discipline as the drug-interaction
// table (architecture rule #9 in spirit). Framing is strictly non-directive
// (PRD §6.1): these are things people find interesting to see over time, never
// safety monitoring, never "you should track X".
//
// Field notation maps onto the existing FIELD_TYPES — no new field kinds:
//   number · scale_1_10 · boolean · freetext · category · multiselect.

export type DiaryTemplate = {
  id: string;
  name: string;
  kind: "medication" | "goal" | "care";
  /** one plain-language sentence — what people commonly track and why it's
   *  interesting over time. Never directive. */
  description: string;
  /** orders / filters visibility only; never auto-selects anything */
  audience?: { sex?: PatientSex; minAge?: number };
  /** lowercased generic drug names that surface this on medication add */
  matchTerms?: string[];
  coreFields: DiaryPreset[]; // default-checked, ≤ 8
  optionalFields: DiaryPreset[]; // default-unchecked
  periodicFields?: DiaryPreset[]; // labs/measurements — "log when you have a result"
};

// ── Terse field builders (group is a display header only; not stored) ────────
const num = (group: string, name: string, unit?: string): DiaryPreset => ({
  name,
  field_type: "number",
  group,
  ...(unit ? { unit } : {}),
});
const scale = (group: string, name: string): DiaryPreset => ({
  name,
  field_type: "scale_1_10",
  group,
});
const yn = (group: string, name: string): DiaryPreset => ({
  name,
  field_type: "boolean",
  group,
});
const text = (group: string, name: string): DiaryPreset => ({
  name,
  field_type: "freetext",
  group,
});
const one = (group: string, name: string, options: string[]): DiaryPreset => ({
  name,
  field_type: "category",
  group,
  category_options: options,
});
const many = (group: string, name: string, options: string[]): DiaryPreset => ({
  name,
  field_type: "multiselect",
  group,
  category_options: options,
});

// ── The launch catalogue (10 templates — the spec's recommended subset) ──────
export const DIARY_TEMPLATES: DiaryTemplate[] = [
  // ── Medication protocol templates ────────────────────────────────────────
  (() => {
    const G = "GLP-1 weight management";
    return {
      id: "glp1-weight",
      name: G,
      kind: "medication" as const,
      description:
        "What people on GLP-1 medications often track — appetite, weight, and how their body settles in.",
      matchTerms: ["semaglutide", "tirzepatide", "liraglutide", "dulaglutide", "retatrutide"],
      coreFields: [
        num(G, "Weight", "lb"),
        scale(G, "Appetite"),
        scale(G, "Food noise"),
        yn(G, "Nausea"),
        scale(G, "Energy"),
        one(G, "Bowel movements", ["None", "Normal", "Constipated", "Loose"]),
        yn(G, "Strength training"),
        yn(G, "Protein target hit"),
      ],
      optionalFields: [
        scale(G, "Satiety after meals"),
        yn(G, "Sulfur burps"),
        yn(G, "Heartburn"),
        yn(G, "Injection site reaction"),
        num(G, "Alcohol", "drinks"),
        num(G, "Water", "cups"),
        num(G, "Sleep", "hours"),
        scale(G, "Mood"),
        many(G, "Cravings", ["Sugar", "Salt", "Carbs", "Alcohol", "None"]),
        yn(G, "Dizziness"),
      ],
      periodicFields: [
        num(G, "Waist", "in"),
        num(G, "Body fat", "%"),
        num(G, "Fasting glucose", "mg/dL"),
        num(G, "Resting heart rate", "bpm"),
      ],
    };
  })(),
  (() => {
    const G = "Testosterone (TRT)";
    return {
      id: "trt-male",
      name: G,
      kind: "medication" as const,
      description:
        "Things people on testosterone often watch over time — energy, mood, sleep, and libido.",
      audience: { sex: "male" as const },
      matchTerms: ["testosterone", "enclomiphene", "hcg"],
      coreFields: [
        scale(G, "Energy"),
        scale(G, "Libido"),
        scale(G, "Mood"),
        scale(G, "Irritability"),
        yn(G, "Morning erections"),
        scale(G, "Sleep quality"),
        scale(G, "Gym performance"),
        yn(G, "Acne"),
      ],
      optionalFields: [
        scale(G, "Erection quality"),
        scale(G, "Motivation"),
        scale(G, "Anxiety"),
        yn(G, "Night sweats"),
        yn(G, "Nipple tenderness"),
        yn(G, "Water retention"),
        one(G, "Hair shedding", ["None", "Mild", "Noticeable"]),
        yn(G, "Injection site reaction"),
        scale(G, "Confidence"),
        scale(G, "Brain fog"),
      ],
      periodicFields: [
        num(G, "Total testosterone", "ng/dL"),
        num(G, "Free testosterone", "pg/mL"),
        num(G, "Estradiol", "pg/mL"),
        num(G, "Hematocrit", "%"),
        num(G, "PSA", "ng/mL"),
        text(G, "Blood pressure"),
        num(G, "Weight", "lb"),
      ],
    };
  })(),
  (() => {
    const G = "Menopause HRT";
    return {
      id: "menopause-hrt",
      name: G,
      kind: "medication" as const,
      description:
        "What people on menopause hormone therapy commonly track — hot flashes, sleep, and mood.",
      audience: { sex: "female" as const },
      matchTerms: ["estradiol", "conjugated estrogens", "progesterone", "estrogen"],
      coreFields: [
        num(G, "Hot flashes", "count"),
        yn(G, "Night sweats"),
        scale(G, "Sleep quality"),
        scale(G, "Mood"),
        scale(G, "Energy"),
        scale(G, "Brain fog"),
        scale(G, "Joint pain"),
        yn(G, "Bleeding or spotting"),
      ],
      optionalFields: [
        scale(G, "Anxiety"),
        scale(G, "Irritability"),
        scale(G, "Libido"),
        scale(G, "Vaginal dryness"),
        yn(G, "Breast tenderness"),
        yn(G, "Headache"),
        yn(G, "Palpitations"),
        yn(G, "Skin dryness"),
        yn(G, "Bloating"),
      ],
      periodicFields: [num(G, "Weight", "lb"), text(G, "Blood pressure")],
    };
  })(),
  (() => {
    const G = "Antidepressant";
    return {
      id: "ssri-snri",
      name: G,
      kind: "medication" as const,
      description:
        "A day-by-day record people on antidepressants often keep — mood, sleep, and how they're feeling.",
      matchTerms: [
        "sertraline", "escitalopram", "fluoxetine", "venlafaxine",
        "duloxetine", "bupropion", "mirtazapine",
      ],
      coreFields: [
        scale(G, "Mood"),
        scale(G, "Anxiety"),
        scale(G, "Sleep quality"),
        scale(G, "Energy"),
        scale(G, "Appetite"),
        yn(G, "Nausea"),
        yn(G, "Headache"),
        yn(G, "Took dose on time"),
      ],
      optionalFields: [
        scale(G, "Libido"),
        scale(G, "Emotional flatness"),
        scale(G, "Restlessness"),
        yn(G, "Vivid dreams"),
        yn(G, "Sweating"),
        scale(G, "Concentration"),
        yn(G, "Social interaction today"),
        yn(G, "Got outside today"),
        yn(G, "Dizziness"),
      ],
      periodicFields: [num(G, "Weight", "lb")],
    };
  })(),
  (() => {
    const G = "ADHD medication";
    return {
      id: "adhd-stimulant",
      name: G,
      kind: "medication" as const,
      description:
        "What people on ADHD medication often track to dial in timing — focus, appetite, and sleep.",
      matchTerms: [
        "methylphenidate", "lisdexamfetamine", "dextroamphetamine",
        "amphetamine", "atomoxetine",
      ],
      coreFields: [
        scale(G, "Focus"),
        scale(G, "Productivity"),
        scale(G, "Appetite"),
        text(G, "Time fell asleep"),
        scale(G, "Irritability"),
        yn(G, "Afternoon crash"),
        scale(G, "Anxiety"),
        num(G, "Caffeine", "cups"),
      ],
      optionalFields: [
        yn(G, "Heart rate awareness"),
        yn(G, "Jaw clenching"),
        scale(G, "Mood"),
        yn(G, "Ate lunch"),
        yn(G, "Hyperfocus episode"),
        text(G, "Dose timing"),
        yn(G, "Headache"),
        scale(G, "Talkativeness"),
      ],
      periodicFields: [
        num(G, "Weight", "lb"),
        num(G, "Resting heart rate", "bpm"),
        text(G, "Blood pressure"),
      ],
    };
  })(),
  (() => {
    const G = "Thyroid";
    return {
      id: "thyroid",
      name: G,
      kind: "medication" as const,
      description:
        "Things people on thyroid medication often watch — energy, temperature, and how they feel between blood tests.",
      matchTerms: ["levothyroxine", "liothyronine", "ndt", "thyroid"],
      coreFields: [
        scale(G, "Energy"),
        one(G, "Cold tolerance", ["Poor", "Okay", "Good"]),
        scale(G, "Mood"),
        scale(G, "Brain fog"),
        one(G, "Bowel regularity", ["Constipated", "Normal", "Loose"]),
        scale(G, "Sleep quality"),
        yn(G, "Heart palpitations"),
        yn(G, "Took dose fasted"),
      ],
      optionalFields: [
        one(G, "Hair shedding", ["None", "Mild", "Noticeable"]),
        yn(G, "Dry skin"),
        num(G, "Weight", "lb"),
        scale(G, "Anxiety"),
        yn(G, "Muscle weakness"),
        yn(G, "Heat intolerance"),
      ],
      periodicFields: [
        num(G, "TSH", "mIU/L"),
        num(G, "Free T4", "ng/dL"),
        num(G, "Free T3", "pg/mL"),
        num(G, "Resting heart rate", "bpm"),
      ],
    };
  })(),
  (() => {
    const G = "Sleep";
    return {
      id: "sleep-med",
      name: G,
      kind: "medication" as const,
      description:
        "A sleep record that pairs the medication with your habits, so you can see what's helping.",
      matchTerms: ["zopiclone", "zolpidem", "trazodone", "melatonin", "doxepin", "suvorexant"],
      coreFields: [
        num(G, "Time to fall asleep", "minutes"),
        num(G, "Sleep", "hours"),
        num(G, "Night wakings", "count"),
        scale(G, "Sleep quality"),
        scale(G, "Morning grogginess"),
        yn(G, "Took sleep aid"),
        yn(G, "Caffeine after 2pm"),
        yn(G, "Screens in bed"),
      ],
      optionalFields: [
        yn(G, "Naps"),
        num(G, "Alcohol", "drinks"),
        yn(G, "Exercise"),
        scale(G, "Stress"),
        yn(G, "Dream recall"),
        text(G, "Out of bed time"),
      ],
    };
  })(),
  // ── Goal templates (no medication required) ──────────────────────────────
  (() => {
    const G = "Weight loss";
    return {
      id: "weight-loss",
      name: G,
      kind: "goal" as const,
      description: "A simple set for a weight goal — weight, food, training, and sleep.",
      coreFields: [
        num(G, "Weight", "lb"),
        yn(G, "Calorie target hit"),
        yn(G, "Protein target hit"),
        num(G, "Steps"),
        yn(G, "Strength training"),
        scale(G, "Hunger"),
        num(G, "Sleep", "hours"),
        num(G, "Alcohol", "drinks"),
      ],
      optionalFields: [
        many(G, "Cravings", ["Sugar", "Salt", "Carbs", "Alcohol", "None"]),
        yn(G, "Late-night eating"),
        num(G, "Water", "cups"),
        scale(G, "Mood"),
        scale(G, "Energy"),
        scale(G, "Stress"),
      ],
      periodicFields: [num(G, "Waist", "in"), yn(G, "Progress photo taken")],
    };
  })(),
  (() => {
    const G = "Cycle & PMS";
    return {
      id: "cycle-pms",
      name: G,
      kind: "goal" as const,
      description:
        "Track your cycle alongside mood and symptoms to spot patterns over the month.",
      audience: { sex: "female" as const },
      coreFields: [
        num(G, "Cycle day", "day"),
        yn(G, "Period today"),
        one(G, "Flow", ["None", "Spotting", "Light", "Medium", "Heavy"]),
        scale(G, "Cramps"),
        scale(G, "Mood"),
        scale(G, "Irritability"),
        scale(G, "Energy"),
        yn(G, "Bloating"),
      ],
      optionalFields: [
        yn(G, "Breast tenderness"),
        yn(G, "Headache"),
        yn(G, "Food cravings"),
        scale(G, "Anxiety"),
        scale(G, "Sleep quality"),
        scale(G, "Libido"),
        yn(G, "Back pain"),
      ],
    };
  })(),
  // ── Care oversight templates ─────────────────────────────────────────────
  (() => {
    const G = "Older-adult wellbeing";
    return {
      id: "older-adult-care",
      name: G,
      kind: "care" as const,
      description:
        "A shared daily check-in for an older adult — appetite, mobility, mood, and sleep, logged by whoever's there.",
      coreFields: [
        one(G, "Appetite", ["Ate well", "Ate some", "Ate little"]),
        one(G, "Fluids", ["Good", "Fair", "Poor"]),
        scale(G, "Mobility today"),
        yn(G, "Confusion or disorientation"),
        scale(G, "Mood"),
        yn(G, "Slept well"),
        yn(G, "Fall or near-fall"),
        scale(G, "Pain"),
      ],
      optionalFields: [
        yn(G, "Bowel movement"),
        yn(G, "Took all medications"),
        yn(G, "Social interaction"),
        yn(G, "Got outside"),
        text(G, "Unusual behavior"),
        yn(G, "Swelling"),
      ],
    };
  })(),
];

// ── Lookups & filtering ──────────────────────────────────────────────────────

/** Medication templates whose matchTerms overlap the drug's canonical name.
 *  Substring either way so "testosterone" matches "testosterone cypionate". */
export function templatesForDrug(
  canonicalName: string | null | undefined
): DiaryTemplate[] {
  const c = (canonicalName ?? "").trim().toLowerCase();
  if (!c) return [];
  return DIARY_TEMPLATES.filter(
    (t) =>
      t.kind === "medication" &&
      (t.matchTerms ?? []).some((term) => {
        const m = term.toLowerCase();
        return c.includes(m) || m.includes(c);
      })
  );
}

export function templateById(id: string): DiaryTemplate | undefined {
  return DIARY_TEMPLATES.find((t) => t.id === id);
}

/** Whether a template should be visible for a patient's demographics. A known
 *  mismatched sex hides it; unknown sex shows everything (the user can still
 *  browse it). Age only hides when both the gate and the age are known. */
export function audienceMatches(
  t: DiaryTemplate,
  opts: { sex?: PatientSex | null; age?: number | null }
): boolean {
  const a = t.audience;
  if (!a) return true;
  if (a.sex && opts.sex && a.sex !== opts.sex) return false;
  if (a.minAge != null && opts.age != null && opts.age < a.minAge) return false;
  return true;
}

/** Templates for the browsable gallery, audience-filtered. */
export function galleryTemplates(opts: {
  sex?: PatientSex | null;
  age?: number | null;
}): DiaryTemplate[] {
  return DIARY_TEMPLATES.filter((t) => audienceMatches(t, opts));
}

/** Whole-years age from an ISO date-of-birth, relative to `now` (ms). */
export function ageFromDob(
  dob: string | null | undefined,
  now: number
): number | null {
  if (!dob) return null;
  const born = new Date(dob).getTime();
  if (!Number.isFinite(born)) return null;
  return Math.floor((now - born) / (365.25 * 86_400_000));
}

export type TemplateBucket = "core" | "optional" | "periodic";

export type TemplateFieldRow = {
  preset: DiaryPreset;
  bucket: TemplateBucket;
  cadence: FieldCadence;
  defaultChecked: boolean;
};

/** Flatten a template into rows for the confirm screen / apply action: core is
 *  checked + daily, optional is unchecked + daily, periodic is unchecked +
 *  periodic (kept off the daily form). */
export function templateFieldRows(t: DiaryTemplate): TemplateFieldRow[] {
  const rows: TemplateFieldRow[] = [];
  for (const preset of t.coreFields) {
    rows.push({ preset, bucket: "core", cadence: "daily", defaultChecked: true });
  }
  for (const preset of t.optionalFields) {
    rows.push({ preset, bucket: "optional", cadence: "daily", defaultChecked: false });
  }
  for (const preset of t.periodicFields ?? []) {
    rows.push({ preset, bucket: "periodic", cadence: "periodic", defaultChecked: false });
  }
  return rows;
}
